-- Vibraweb baseline for Neon.
-- Keeps the existing app schema compatible while Neon Auth stores users in neon_auth.user.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.current_user_id()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
  SELECT NULLIF(current_setting('request.jwt.claims', true)::jsonb ->> 'sub', '')::uuid;
$$;

CREATE TABLE IF NOT EXISTS public.user_profiles (
  id uuid PRIMARY KEY REFERENCES neon_auth."user"(id) ON DELETE CASCADE,
  consultant_name text NOT NULL DEFAULT '',
  consultant_contact text NOT NULL DEFAULT '',
  logo_url text,
  plan text NOT NULL DEFAULT 'free' CHECK (plan IN ('free', 'pro')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.interpretacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero integer NOT NULL,
  tipo text NOT NULL,
  titulo text NOT NULL,
  texto text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (numero, tipo)
);

CREATE TABLE IF NOT EXISTS public.analyses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES neon_auth."user"(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('pessoal', 'bebe', 'empresa', 'previsoes')),
  subject text,
  input_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  result_data jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.user_profiles (id, consultant_name)
  VALUES (NEW.id, COALESCE(NEW.name, ''))
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_neon_auth_user_created ON neon_auth."user";
CREATE TRIGGER on_neon_auth_user_created
AFTER INSERT ON neon_auth."user"
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();

ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interpretacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analyses ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anonymous, authenticated;
GRANT SELECT ON public.interpretacoes TO anonymous, authenticated;
GRANT SELECT, UPDATE ON public.user_profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.analyses TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anonymous, authenticated;

DROP POLICY IF EXISTS "Public read interpretations" ON public.interpretacoes;
CREATE POLICY "Public read interpretations"
  ON public.interpretacoes
  FOR SELECT
  TO anonymous, authenticated
  USING (true);

DROP POLICY IF EXISTS "Users read own profile" ON public.user_profiles;
CREATE POLICY "Users read own profile"
  ON public.user_profiles
  FOR SELECT
  TO authenticated
  USING (public.current_user_id() = id);

DROP POLICY IF EXISTS "Users update own profile" ON public.user_profiles;
CREATE POLICY "Users update own profile"
  ON public.user_profiles
  FOR UPDATE
  TO authenticated
  USING (public.current_user_id() = id)
  WITH CHECK (public.current_user_id() = id);

DROP POLICY IF EXISTS "Users manage own analyses" ON public.analyses;
CREATE POLICY "Users manage own analyses"
  ON public.analyses
  FOR ALL
  TO authenticated
  USING (public.current_user_id() = user_id)
  WITH CHECK (public.current_user_id() = user_id);

CREATE INDEX IF NOT EXISTS analyses_user_updated_idx
  ON public.analyses (user_id, updated_at DESC);
