-- Migration 007: Seed Definições dos Pilares
-- Cria os textos explicativos estáticos para cada parte do mapa numerológico.

INSERT INTO public.interpretacoes (numero, tipo, titulo, texto) VALUES
(1, 'estatico_def_motivacao', 'Definição de Motivação', 'O número de Motivação descreve os motivos e as razões que movem as atitudes do ser humano e o seu modo de proceder. Este número revela o aspecto interior da personalidade; reflete as atitudes e comportamentos, principalmente na intimidade e no lar, influenciando ainda nas escolhas pessoais. Nem sempre há coerência, pois, a atitude interior da pessoa, muitas vezes, não é revelada para os outros, mas rege as suas decisões intuitivas. O número de Motivação revela as crenças e os valores internos da pessoa e mobiliza seus ideais, seus desejos, suas ambições, a vontade e os sentimentos mais íntimos que o impulsionam a buscar determinados caminhos para as suas realizações na vida. Revela a essência da personalidade.'),
(1, 'estatico_def_impressao', 'Definição de Impressão', 'O número de Impressão (ou Aparência) revela a forma como você se apresenta ao mundo e como as outras pessoas o percebem à primeira vista. Representa a sua "roupagem" externa, o seu estilo pessoal, as suas reações automáticas em ambientes sociais e o impacto inicial que você causa antes mesmo de falar. Ele descreve a imagem pública que você projeta, as características físicas e comportamentais que ficam evidentes para o observador externo. Em muitas ocasiões, a Impressão atua como um escudo ou uma ponte, facilitando ou dificultando as suas conexões sociais de acordo com a sintonia entre a sua essência interior e a imagem que você transmite para a sociedade.'),
(1, 'estatico_def_expressao', 'Definição de Expressão', 'O número de Expressão sintetiza a soma total de seus talentos, aptidões e potenciais naturais. Ele descreve a maneira como você se expressa na vida, a sua verdadeira vocação e os instrumentos que você possui para interagir com o mundo e alcançar seus objetivos. Representando a totalidade do nome de nascimento, a Expressão é a união da sua essência interior (Motivação) com a sua imagem exterior (Impressão). Este número revela as suas maiores habilidades, os traços marcantes da sua personalidade em plena atividade e a forma como você aplica a sua inteligência e energia no ambiente profissional e nas suas relações ao longo da vida.'),
(1, 'estatico_def_talento_oculto', 'Definição de Talento Oculto', 'O Talento Oculto representa uma habilidade latente, um dom adormecido que muitas vezes passa despercebido ou é subutilizado ao longo da vida. Ele revela uma força secundária que, quando ativada e desenvolvida com consciência, pode servir como um trunfo valioso para auxiliar na superação de bloqueios e na potencialização da sua Expressão e do seu Destino. É uma qualidade sutil, uma sabedoria ou aptidão instintiva que aflora em momentos de necessidade ou através de práticas de autoconhecimento, fornecendo as ferramentas adicionais para que você alcance um estado de maior plenitude e eficácia nas suas realizações profissionais e pessoais.'),
(1, 'estatico_def_aptidoes', 'Definição de Aptidões Profissionais', 'As Aptidões Profissionais revelam as áreas de atuação, os talentos e as inclinações onde você possui maior facilidade para alcançar o sucesso material e a satisfação no trabalho. Baseado na vibração do seu número de Expressão, este índice aponta não apenas as profissões e carreiras mais harmônicas com a sua natureza, mas também o seu estilo de liderança, a sua capacidade de colaboração e os ambientes onde a sua produtividade e criatividade fluem de forma mais natural. Conhecer as suas aptidões é o primeiro passo para alinhar a sua escolha profissional com o seu propósito de vida, transformando o trabalho em uma verdadeira fonte de autorrealização.'),
(1, 'estatico_def_psiquico', 'Definição de Número Psíquico', 'O Número Psíquico, derivado do seu dia de nascimento, é a vibração que rege a sua força interior profunda, o seu temperamento instintivo e os seus dons inatos. Ele descreve como você enxerga o mundo através dos seus próprios olhos e como processa intimamente as experiências da vida antes de agir. É a base da sua identidade psíquica, moldando as suas afinidades, os seus gostos, os seus reflexos emocionais e a maneira como você lida com os estímulos externos. Esta vibração é particularmente ativa nas suas relações mais próximas e íntimas, servindo como a matriz original de onde brotam as suas atitudes mais genuínas e espontâneas.'),
(1, 'estatico_def_destino', 'Definição de Destino', 'O Destino é a soma da sua data de nascimento e representa o caminho de vida que você foi chamado a trilhar. Ele indica a direção principal da sua jornada, as oportunidades que surgirão e os cenários que você atrairá para o seu desenvolvimento evolutivo. O número de Destino mostra o que você veio aprender, as lições fundamentais que a vida lhe exigirá e o propósito maior que deve guiar as suas decisões. Diferente da personalidade (o que você é), o Destino revela a sua trajetória (para onde você vai e o que precisa construir). Ele é o mapa do tesouro que, se seguido com sabedoria, conduzirá à sua máxima realização pessoal, material e espiritual.'),
(1, 'estatico_def_missao', 'Definição de Missão', 'A Missão é a síntese suprema, a fusão entre o que você é (Expressão/Nome) e o caminho que você trilha (Destino/Data de Nascimento). Ela representa a sua verdadeira destinação na vida, o legado que você está destinado a deixar para o mundo e para as pessoas ao seu redor. A Missão revela o ponto de equilíbrio final da sua evolução atual, a vocação que, quando abraçada, traz o sentimento de preenchimento absoluto. Cumprir a sua missão significa utilizar todos os seus talentos e superar todos os seus desafios em prol de algo maior, irradiando a sua luz única e contribuindo ativamente para a evolução.')
ON CONFLICT (numero, tipo) 
DO UPDATE SET texto = EXCLUDED.texto;
