-- Migration 011: Seed Textos de Talento Oculto
-- Cria os textos interpretativos para os números de Talento Oculto (1 a 9, 11 e 22).

INSERT INTO public.interpretacoes (numero, tipo, titulo, texto) VALUES
(1, 'pessoal_talentoOculto', 'Talento Oculto 1', 'Revela um novo talento para a liderança autônoma, a inventividade e a capacidade de iniciativa; pode ser uma ampliação dos seus talentos caracterizados em sua personalidade. O despertar de uma coragem instintiva que conduz à ação direta, equilibrando a vontade de inovar com a autoconfiança inabalável; poder de decisão rápida; capacidade de desbravar caminhos virgens e assumir a vanguarda. Negativamente, pode surgir a arrogância, a teimosia autoritária ou a dificuldade em ouvir conselhos alheios. De qualquer maneira sempre será um aperfeiçoamento de seus talentos, quase como um dom intuitivo inato que se projeta na personalidade.'),

(2, 'pessoal_talentoOculto', 'Talento Oculto 2', 'Revela um novo talento para a mediação, a diplomacia e a sintonia emocional com o ambiente; pode ser uma ampliação dos seus talentos caracterizados em sua personalidade. O despertar da sensibilidade afetiva que conduz à conciliação, equilibrando as divergências com empatia e tato; cooperação genuína e pacificação; amplitude da percepção sobre os sentimentos dos outros. Negativamente, pode surgir a submissão, a dependência emocional ou o medo da rejeição. De qualquer maneira sempre será um aperfeiçoamento de seus talentos, quase como um dom intuitivo inato que se projeta na personalidade.'),

(3, 'pessoal_talentoOculto', 'Talento Oculto 3', 'Revela um novo talento para a comunicação criativa, a expressão artística e a alegria contagiante; pode ser uma ampliação dos seus talentos caracterizados em sua personalidade. O despertar do magnetismo pessoal que conduz à oratória brilhante, equilibrando a imaginação fértil com a capacidade de inspirar multidões; entusiasmo vibrante e sociabilidade; amplitude do senso estético e do humor. Negativamente, pode surgir a dispersão, a superficialidade ou a necessidade excessiva de aplausos. De qualquer maneira sempre será um aperfeiçoamento de seus talentos, quase como um dom intuitivo inato que se projeta na personalidade.'),

(4, 'pessoal_talentoOculto', 'Talento Oculto 4', 'Revela um novo talento para a organização lógica, a gestão pragmática e a construção de bases seguras; pode ser uma ampliação dos seus talentos caracterizados em sua personalidade. O despertar do raciocínio metódico que conduz à eficiência, equilibrando ideias abstratas com disciplina estrutural; lealdade inabalável e resiliência; amplitude na capacidade de planejar a longo prazo e concretizar. Negativamente, pode surgir a rigidez extrema, o excesso de ceticismo ou o autoritarismo rotineiro. De qualquer maneira sempre será um aperfeiçoamento de seus talentos, quase como um dom intuitivo inato que se projeta na personalidade.'),

(5, 'pessoal_talentoOculto', 'Talento Oculto 5', 'Revela um novo talento para a rápida adaptação, a investigação ousada e a libertação de amarras; pode ser uma ampliação dos seus talentos caracterizados em sua personalidade. O despertar da curiosidade perspicaz que conduz à inovação, equilibrando o desejo de aventura com a agilidade mental; versatilidade extraordinária e coragem para o risco; amplitude dos horizontes experienciais e culturais. Negativamente, pode surgir a impulsividade inconsequente, a irresponsabilidade ou a inquietação crônica. De qualquer maneira sempre será um aperfeiçoamento de seus talentos, quase como um dom intuitivo inato que se projeta na personalidade.'),

(6, 'pessoal_talentoOculto', 'Talento Oculto 6', 'Revela um novo talento para o aconselhamento acolhedor, a cura emocional e a responsabilidade comunitária; pode ser uma ampliação dos seus talentos caracterizados em sua personalidade. O despertar do amor cuidadoso que conduz à harmonia familiar, equilibrando o senso estético com a profunda empatia maternal ou paternal; senso de justiça e devoção ao bem-estar coletivo; amplitude na capacidade de nutrir as pessoas. Negativamente, pode surgir o perfeccionismo sufocante, o vitimismo ou a interferência excessiva na vida alheia. De qualquer maneira sempre será um aperfeiçoamento de seus talentos, quase como um dom intuitivo inato que se projeta na personalidade.'),

(7, 'pessoal_talentoOculto', 'Talento Oculto 7', 'Revela um novo talento para a análise minuciosa, a pesquisa aprofundada e a sabedoria filosófica; pode ser uma ampliação dos seus talentos caracterizados em sua personalidade. O despertar da introspecção investigativa que conduz à verdade, equilibrando o pensamento lógico com a intuição aguçada; erudição e especialização técnica; amplitude na compreensão dos grandes mistérios da vida e do oculto. Negativamente, pode surgir a melancolia, o isolamento excessivo ou o cinismo aristocrático. De qualquer maneira sempre será um aperfeiçoamento de seus talentos, quase como um dom intuitivo inato que se projeta na personalidade.'),

(8, 'pessoal_talentoOculto', 'Talento Oculto 8', 'Revela um novo talento para o comando executivo, a administração financeira e a conquista material; pode ser uma ampliação dos seus talentos caracterizados em sua personalidade. O despertar do instinto de poder que conduz à autoridade justa, equilibrando a ambição com a visão estratégica de longo alcance; excelência gerencial e resiliência empresarial; amplitude na capacidade de transformar esforço em riqueza concreta. Negativamente, pode surgir a ganância, a frieza calculista ou a intimidação tirânica. De qualquer maneira sempre será um aperfeiçoamento de seus talentos, quase como um dom intuitivo inato que se projeta na personalidade.'),

(9, 'pessoal_talentoOculto', 'Talento Oculto 9', 'Revela um novo talento para o altruísmo universal, a visão humanitária global e a tolerância incondicional; pode ser uma ampliação dos seus talentos caracterizados em sua personalidade. O despertar da compaixão elevada que conduz ao amor sem fronteiras, equilibrando a sabedoria inata com a vontade de servir ao próximo; filantropia e desapego; amplitude da compreensão moral e da empatia espiritual. Negativamente, pode surgir a desilusão amarga, o excesso de emotividade dramática ou a falta de praticidade cotidiana. De qualquer maneira sempre será um aperfeiçoamento de seus talentos, quase como um dom intuitivo inato que se projeta na personalidade.'),

(11, 'pessoal_talentoOculto', 'Talento Oculto 11', 'Revela um novo talento para uma liderança motivada por ideais superiores e diplomacia visionária; pode ser uma ampliação dos seus talentos caracterizados em sua personalidade. O despertar da inteligência espiritual que conduz à razão iluminada, equilibrando as emoções com o pensamento elevado; humanização, clarividência e espiritualidade; amplitude dos horizontes da intuição e do intelecto inspirado. Negativamente, pode surgir instabilidade nervosa, fanatismo ou dúvidas sobre as próprias capacidades. De qualquer maneira sempre será um aperfeiçoamento de seus talentos, quase como um dom intuitivo inato que se projeta na personalidade.'),

(22, 'pessoal_talentoOculto', 'Talento Oculto 22', 'Revela um novo talento para a arquitetura de sistemas sociais, a liderança colossal e a construção de legados históricos; pode ser uma ampliação dos seus talentos caracterizados em sua personalidade. O despertar da genialidade prática que conduz a realizações monumentais, equilibrando a utopia espiritual com a mais severa eficiência material; diplomacia macroeconômica e poder organizacional; amplitude na capacidade de transformar o mundo em escala global. Negativamente, pode surgir o medo do próprio potencial, a ambição implacável ou a corrupção pelo poder extremo. De qualquer maneira sempre será um aperfeiçoamento de seus talentos, quase como um dom intuitivo inato que se projeta na personalidade.')

ON CONFLICT (numero, tipo) 
DO UPDATE SET 
  titulo = EXCLUDED.titulo,
  texto = EXCLUDED.texto;
