-- Migration 026: Seed Definições (introdução) das categorias adicionadas
-- nesta sessão à grade de Números — mesma família de textos estáticos que a
-- migration 007 (numero=1, tipo `estatico_def_<categoria>`), lidos em
-- document-builder.ts como o parágrafo de abertura de cada bloco do
-- relatório. Sem isso, "Introduções de Categoria" mostrava "0 de 9" e nunca
-- crescia mesmo com novas categorias na grade de Números.

INSERT INTO public.interpretacoes (numero, tipo, titulo, texto) VALUES
(1, 'estatico_def_licao_carmica', 'Definição de Lições Cármicas', 'As Lições Cármicas são reveladas pelos números ausentes no seu nome de nascimento — vibrações que você ainda não experimentou o suficiente em vidas ou fases anteriores e que, por isso, chegam nesta existência como lacunas a preencher. Cada número faltante aponta uma qualidade específica que precisa ser conscientemente desenvolvida através do esforço e da repetição, já que ela não vem como um talento natural. Reconhecer as suas Lições Cármicas é um convite à humildade: são áreas onde o crescimento exige mais disciplina, mas que, uma vez trabalhadas, tornam-se algumas das conquistas mais sólidas e duradouras da sua trajetória.'),

(1, 'estatico_def_debito_carmico', 'Definição de Débitos Cármicos', 'Os Débitos Cármicos são números específicos (13, 14, 16 e 19) que, quando presentes nos cálculos centrais do mapa, indicam um padrão de comportamento do passado que precisa ser reequilibrado nesta vida. Diferente de uma "punição", trata-se de um convite ao amadurecimento consciente: cada débito aponta uma tendência específica — desde a resistência ao esforço disciplinado até o abuso da liberdade ou do poder pessoal — que, se ignorada, tende a se repetir como obstáculo, e que, se enfrentada de frente, se transforma em uma das maiores fontes de força de caráter da pessoa.'),

(1, 'estatico_def_desafio', 'Definição de Desafios', 'Os números de Desafio revelam os obstáculos internos mais recorrentes ao longo da vida — as dificuldades que se repetem em diferentes contextos e que pedem atenção redobrada em determinados períodos. Calculados a partir da data de nascimento, eles não descrevem eventos externos, mas sim os padrões de reação e as armadilhas emocionais ou comportamentais que tendem a se manifestar sempre que a pessoa é colocada sob pressão. Conhecer os seus Desafios é uma ferramenta de autoconhecimento: permite antecipar os pontos de atrito antes que eles se tornem crises e trabalhar preventivamente as qualidades que os neutralizam.'),

(1, 'estatico_def_ciclo', 'Definição de Ciclos de Vida', 'Os Ciclos de Vida dividem a existência em três grandes fases — juventude, maturidade e terceira idade — cada uma regida por um número que indica o "clima" energético predominante daquele período: as oportunidades mais favoráveis, os temas centrais de aprendizado e o tipo de experiência que tende a se repetir. Compreender em qual ciclo você está e qual número o rege ajuda a alinhar as suas escolhas com o momento certo da vida, evitando forçar contra a maré ou desperdiçar janelas de oportunidade que só aquele ciclo específico oferece.'),

(1, 'estatico_def_resposta_subconsciente', 'Definição de Resposta Subconsciente', 'A Resposta Subconsciente mede, através da quantidade de números diferentes presentes no seu nome de nascimento (de 0 a 9), o quão rapidamente e com quantos recursos internos você reage diante de situações inesperadas ou de crise. Quanto mais números presentes, maior o repertório automático de respostas disponíveis; quanto menos, maior a tendência a hesitar ou improvisar diante do imprevisto — não por falta de capacidade, mas por menor variedade de "ferramentas" subconscientes já desenvolvidas. É um indicador de resiliência instintiva, útil para entender o próprio ritmo de adaptação diante do inesperado.'),

(1, 'estatico_def_harmonia_conjugal', 'Definição de Harmonia Conjugal', 'A Harmonia Conjugal, calculada a partir do número de Missão, indica com quais vibrações a sua energia se relaciona de forma mais fluida, harmoniosa ou desafiadora nos vínculos afetivos e nas parcerias de vida. Números "que vibram" e "que atraem" tendem a gerar conexões naturais e complementares; números "opostos" ou "passivos" não impedem o relacionamento, mas pedem mais consciência, diálogo e ajuste mútuo para que a diferença se torne complementaridade em vez de atrito. Esta análise é um retrato energético, não uma sentença — toda relação evolui com autoconhecimento de ambas as partes.'),

(1, 'estatico_def_ano_pessoal', 'Definição de Ano Pessoal', 'O Ano Pessoal é uma vibração que se renova a cada aniversário e indica o "clima" energético predominante para os doze meses seguintes — as oportunidades mais favoráveis, os temas centrais e o tipo de energia disponível para agir. Ele funciona como uma bússola de curto prazo: alinhar as suas decisões com a vibração do Ano Pessoal atual ajuda a aproveitar o timing certo de cada fase, seja para iniciar (anos de número 1), consolidar (anos de número 4 ou 8), ou encerrar ciclos e se preparar para o próximo (anos de número 9).'),

(1, 'estatico_def_mes_pessoal', 'Definição de Mês Pessoal', 'O Mês Pessoal refina a vibração do Ano Pessoal em ciclos mensais, indicando variações mais sutis e específicas de energia dentro do mesmo ano — momentos mais propícios para iniciativas, para recolhimento, para socializar ou para concluir pendências. Observar a sequência dos Meses Pessoais ao longo dos próximos doze meses permite um planejamento mais fino das ações, aproveitando as janelas de energia mais alinhadas com cada tipo de objetivo, sem forçar contra o fluxo natural de cada fase.'),

(1, 'estatico_def_dia_pessoal', 'Definição de Dia Pessoal', 'O Dia Pessoal é a vibração numerológica mais imediata do mapa, renovada a cada 24 horas dentro do ciclo do Mês e do Ano Pessoal. Ele indica o tom energético de um dia específico — se é mais propício à ação, à introspecção, à comunicação ou ao descanso — funcionando como uma leitura de curtíssimo prazo, útil para decidir o melhor momento para uma conversa importante, uma assinatura, um início ou uma pausa necessária.')
ON CONFLICT (numero, tipo)
DO UPDATE SET texto = EXCLUDED.texto, titulo = EXCLUDED.titulo;
