-- Migration 029: Seed Ano Pessoal 1-9 — categoria existia na grade de
-- Números e no bloco "Previsões Temporais" (numEntry com defKey já
-- corretamente ligado), mas nunca teve nenhum texto padrão cadastrado — o
-- documento gerado sempre caía no fallback "Consulte um numerólogo...".
-- Ano Pessoal não usa números mestres (confirmado: pdf-ano-pessoal.pdf,
-- "O Ano Pessoal, que vai do 1 até o 9").

INSERT INTO public.interpretacoes (numero, tipo, titulo, texto) VALUES
(1, 'pessoal_anoPessoal', 'Ano Pessoal 1 — Começar', 'Este é o ano de iniciar coisas novas — ele estabelece o tom de todo o ciclo de nove anos que se abre agora. É tempo de tomar a frente, mostrar coragem e definir os rumos que vai seguir, apoiando-se na sua própria intuição e independência. A principal armadilha é a inércia: adiar o início de algo importante pode gerar uma apatia que se arrasta pelo ciclo inteiro. Aproveite as oportunidades inesperadas que surgirem e desenvolva a confiança de que este é o momento certo para plantar as sementes que vai colher nos próximos anos.'),

(2, 'pessoal_anoPessoal', 'Ano Pessoal 2 — Cooperar', 'Este é um ano para agir com discrição, paciência e receptividade às ideias dos outros, deixando o protagonismo em segundo plano. É uma fase favorável para relacionamentos, parcerias e amizades, mas pede que tudo aconteça em ritmo mais lento do que o do ano anterior. As armadilhas a evitar são a hipersensibilidade e a tendência a se envolver em discussões desnecessárias. Diplomacia, colaboração e a disposição para ouvir mais do que falar são os ingredientes que tornam este ano produtivo.'),

(3, 'pessoal_anoPessoal', 'Ano Pessoal 3 — Expressar', 'Este é um ano de vida social intensa e boa disposição, favorável para diversão, viagens e para dar vazão à sua criatividade através da palavra, da escrita ou de qualquer forma de expressão pessoal. É também um período propenso a envolvimentos afetivos e novas amizades. A armadilha a evitar é a extravagância — tanto emocional quanto financeira — que pode gerar dificuldades logo no ano seguinte se os excessos não forem contidos. Aproveite a energia leve e comunicativa deste ano para se conectar e se mostrar ao mundo.'),

(4, 'pessoal_anoPessoal', 'Ano Pessoal 4 — Construir', 'Este é um ano de trabalho duro, disciplina e construção de bases sólidas para o futuro — não à toa, também costuma trazer mais despesas e restrições do que os anteriores. É um bom momento para organizar finanças, cuidar de imóveis e propriedades, e estruturar metodicamente aquilo que foi lançado nos anos anteriores do ciclo. A armadilha a evitar é negligenciar a própria saúde em meio ao excesso de trabalho. Persistência e método, mais do que velocidade, são o que garante resultado neste ano.'),

(5, 'pessoal_anoPessoal', 'Ano Pessoal 5 — Mudar', 'Este é um ano de ritmo acelerado, mudanças inesperadas e pouca previsibilidade — sendo o ponto central do ciclo de nove anos, ele pede que você viva mais o presente do que faça planos de longo prazo. É um período favorável para se adaptar, aproveitar oportunidades antes que se percam e desenvolver a própria versatilidade diante do imprevisto. As armadilhas a evitar são a dispersão de energia e o uso irresponsável da liberdade pessoal, que podem comprometer conquistas dos anos anteriores. Flexibilidade é a palavra-chave deste ano.'),

(6, 'pessoal_anoPessoal', 'Ano Pessoal 6 — Cuidar', 'Este é um ano voltado para o casamento, a família e as responsabilidades domésticas, no qual os relacionamentos mais próximos pedem atenção e dedicação especial. É um bom período para resolver pendências afetivas, fortalecer vínculos e, se for o caso, iniciar um relacionamento sério ou até um casamento. As armadilhas a evitar são o idealismo excessivo e a tendência a exigir demais dos outros. Serviço, cuidado e presença são o que trazem os melhores resultados neste ano.'),

(7, 'pessoal_anoPessoal', 'Ano Pessoal 7 — Recolher', 'Este é um ano de introspecção, estudo e aperfeiçoamento interior, no qual as atividades puramente materialistas tendem a render menos do que o esperado. É um período propício para se dedicar a assuntos espirituais, filosóficos ou intelectuais, e para deixar que as coisas aconteçam em um ritmo mais lento e reflexivo. As armadilhas a evitar são negligenciar a saúde e forçar decisões importantes antes da hora. Quanto menor a ambição por resultados imediatos, melhores tendem a ser os frutos colhidos mais à frente.'),

(8, 'pessoal_anoPessoal', 'Ano Pessoal 8 — Realizar', 'Este é um ano dinâmico e materialista, no qual os negócios tendem a prosperar e o dinheiro pode surgir de fontes inesperadas — mas também é um ano de grandes cobranças, já que é o momento de colher o que foi plantado ao longo do ciclo. É uma excelente fase para negociações, decisões financeiras importantes e para assumir posições de maior responsabilidade. A armadilha a evitar é deixar a emotividade excessiva atrapalhar decisões que pedem organização e bom senso prático. Coragem, eficiência e ética no uso do poder pessoal são o que garante os melhores resultados.'),

(9, 'pessoal_anoPessoal', 'Ano Pessoal 9 — Concluir', 'Este é um ano de finalizações — encerra o ciclo de nove anos e pede que você se livre de tudo o que já não serve mais, sejam pessoas, situações ou crenças ultrapassadas. É um período propício para viagens, estudos, atividades humanitárias e para praticar o desapego emocional diante do que está se encerrando. As armadilhas a evitar são o ciúme e a possessividade diante das mudanças que este ano naturalmente traz. Fechar bem este ciclo é o que garante um início leve e promissor no próximo ano pessoal 1.')
ON CONFLICT (numero, tipo)
DO UPDATE SET texto = EXCLUDED.texto, titulo = EXCLUDED.titulo;
